Assign resources to gateway
grafana/tempo-operator pull request #404
Opened 2023-05-05 20:35 UTC by rubenvp8510

This PR assign resources to the tempo gateway

In order to determine what percentage of resources the gateway needs I did some experiments, stressed a tempo stack with a lot of spans, and some queries (this part was done manually) thought the gateway.

Then try to reach the stack ingestion/qquery limits with the assigned resources, based on the gateway consuption did the math.

We can find more about the experiments here: https://docs.google.com/spreadsheets/d/1rqsh2aKxP24FmgQmC9_Ld_qxtXpoNE7yLaoy1fzjRko/edit?usp=sharing

I have to round the numbers manually so the sum will be 1.0

2023-05-08 10:18 UTC, iblancasa approved these changes

2023-05-08 12:01 UTC, andreasgerstmayr approved these changes

2023-05-09 07:39 UTC, pavolloffay requested changes
The PR should set resources on the gateway deployment https://github.com/grafana/tempo-operator/blob/main/internal/manifests/gateway/gateway.go#LL215C1-L216C1

2023-05-09 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/tempo-operator?pullRequest=404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/tempo-operator?pullRequest=404) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/tempo-operator?pullRequest=404) it.</sub>

2023-05-09 13:51 UTC, rubenvp8510 commented
> The PR should set resources on the gateway deployment https://github.com/grafana/tempo-operator/blob/main/internal/manifests/gateway/gateway.go#LL215C1-L216C1

Ooops, forgot to commit that file

2023-05-09 16:00 UTC, pavolloffay commented
@rubenvp8510 e2e test failed. could you please squash commits?

2023-05-10 16:05 UTC, rubenvp8510 commented
This is ready for other review and merge :)

2023-05-11 08:00 UTC, merged